### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by RichieB2B** [michaelherger/spotty#30]
I just wanted to leave this here. Happens every week or so using Spotty v4.6.2. I have enabled debug logging for `plugin.spotty` now.
```
Nov 24 12:42:46 nasty squeezeboxserver[3917482]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: UnexpectedEof, error: "early eof" })', src/spotty.rs:113:26
Nov 24 12:42:46 nasty squeezeboxserver[3917482]: stack backtrace:
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    0:           0x6cbd0a - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    1:           0x44966f - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    2:           0x6cb491 - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    3:           0x6caed0 - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    4:           0x6ca497 - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    5:           0x6e683d - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    6:           0x6e67ac - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    7:           0x6e675d - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    8:           0x4005f0 - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:    9:           0x400ce2 - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:   10:           0x43cf77 - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:   11:           0x6b050c - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:   12:           0x6beab3 - <unknown>
Nov 24 12:42:46 nasty squeezeboxserver[3917482]:   13:           0x6af930 - <unknown>
```

**Comment by michaelherger** [comment]
Please be careful with `plugin.spotty` logging: it's super noisy and can create huge log files!

Most likely this crash is due to some temporary networking issue. Is this for the Connect daemon or when you try to play a track?

**Comment by RichieB2B** [comment]
I'm not sure. I'll try to correlate this to our use of Spotty next time it happens.

**Comment by RichieB2B** [comment]
I received another panic this morning just like the one above but with a different `spotty.rs` line number. It was a t 2:30 AM. It is safe to say no-one in my household was interacting with Spotty at that time.
```
Jan  3 02:30:24 nasty squeezeboxserver[1508964]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: UnexpectedEof, error: "early eof" })', src/spotty.rs:68:22
Jan  3 02:30:24 nasty squeezeboxserver[1508964]: stack backtrace:
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    0:           0x6cbd0a - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    1:           0x44966f - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    2:           0x6cb491 - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    3:           0x6caed0 - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    4:           0x6ca497 - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    5:           0x6e683d - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    6:           0x6e67ac - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    7:           0x6e675d - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    8:           0x4005f0 - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:    9:           0x400ce2 - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:   10:           0x43cf77 - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:   11:           0x6b050c - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:   12:           0x6beab3 - <unknown>
Jan  3 02:30:24 nasty squeezeboxserver[1508964]:   13:           0x6af930 - <unknown>
```

I was not using debug logging at this moment but `server.log` does show something interesting 10 minutes earlier:
```
[22-01-03 02:20:39.0421] Plugins::Spotty::API::Token::_killTokenHelper (179) Timed out waiting for a token
```

**Comment by michaelherger** [comment]
Do you still get these traces with the latest release?

**Comment by RichieB2B** [comment]
I have just updated Spotty to 4.8.1. I'll let you know if that changes these crashes.

**Comment by michaelherger** [comment]
Recent  spotty actually is built right off of my https://github.com/michaelherger/librespot fork.
